(module
  (func (export "test") (param i32) (result i32)
    (i32.const 0)
    (loop (param i32) (result i32)
      (local.get 0)
      (i32.const 1)
      (i32.sub)
      (local.set 0)
      (local.get 0)
      (i32.const 0)
      (i32.le_s)
      (br_if 0)
      (i32.const 1)
      (i32.add)
    )
  )
)
